# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X7ujjPP8OGJNCg9dZyViiwZYAYhlJoSP
"""

import streamlit as st
import numpy as np
import onnxruntime as rt

sess = rt.InferenceSession("diabetes_model.onnx")

input_name = sess.get_inputs()[0].name

st.title("🩺 Diabetes Prediction App")
st.write("Answer the following questions to check your risk for diabetes.")

# User inputs
pregnancies = st.number_input("Number of Pregnancies", min_value=0, max_value=20, value=0)
glucose = st.number_input("Glucose Level", min_value=0, max_value=300, value=120)
blood_pressure = st.number_input("Blood Pressure", min_value=0, max_value=200, value=70)
skin_thickness = st.number_input("Skin Thickness", min_value=0, max_value=100, value=20)
insulin = st.number_input("Insulin Level", min_value=0, max_value=900, value=80)
bmi = st.number_input("BMI", min_value=0.0, max_value=70.0, value=25.0)
dpf = st.number_input("Diabetes Pedigree Function", min_value=0.0, max_value=2.5, value=0.5)
age = st.number_input("Age", min_value=1, max_value=120, value=30)

if st.button("Predict"):
    # Prepare data
    input_data = np.array([[pregnancies, glucose, blood_pressure, skin_thickness, insulin, bmi, dpf, age]],
                          dtype=np.float32)

    # Run model
    prob = sess.run(None, {input_name: input_data})[0]

    # Handle different output shapes (scalar, 1D, or 2D)
    if isinstance(prob, (list, np.ndarray)):
        if np.ndim(prob) == 0:  # Scalar
            probability = float(prob)
        elif np.ndim(prob) == 1:  # 1D array
            probability = float(prob[0])
        else:  # 2D array
            probability = float(prob[0][0])
    else:
        probability = float(prob)

    # Make prediction (threshold 0.5)
    prediction = int(probability > 0.5)

    # Display result
    st.write(f"**Predicted Probability:** {probability:.2f}")
    if prediction == 1:
        st.error("🚨 High risk of Diabetes. Please consult a doctor.", icon="⚠️")
    else:
        st.success("✅ Low risk of Diabetes. Keep up the healthy lifestyle!", icon="💚")