# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qc3U-LiLKKxeIdAa1L-oBrwinGQCJXtu
"""

import streamlit as st
import onnxruntime as rt
import numpy as np

st.title("ONNX Model Prediction")

# تحميل ملف الموديل من المسار المحلي (مثلاً نفس مجلد الكود)
model_path = "decision_tree_model (1).onnx" # اسم ملف الموديل

# تحميل الموديل
sess = rt.InferenceSession(model_path)

# عدد الميزات (features) المطلوبة
num_features = sess.get_inputs()[0].shape[1]
st.write(f"The model requires {num_features} feature(s).")

# إدخال المستخدم لقيم الفيتشرز
feature_input = st.text_input(f"Enter {num_features} feature values separated by commas:")

if st.button("Predict"):
    try:
        input_data = np.array([list(map(float, feature_input.split(',')))], dtype=np.float32)
        if input_data.shape[1] != num_features:
            st.error(f"Please enter exactly {num_features} values.")
        else:
            input_name = sess.get_inputs()[0].name
            prediction = sess.run(None, {input_name: input_data})[0]
            st.success(f"Prediction: {prediction}")
    except Exception as e:
        st.error("Invalid input. Please enter numeric values separated by commas.")